#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_TX_PIN GP1

#define EE_HANDS

#define TAPPING_TERM 250
#define FLOW_TAP_TERM 50

#define WS2812_DI_PIN GP0
#define RGBLIGHT_LED_COUNT 5
#define RGBLIGHT_SPLIT
